@Contactum.Api_HostAddress = http://localhost:5251

### Get Company By Id
GET {{Contactum.Api_HostAddress}}/api/company/getCompanyById?id=1
Accept: application/json

###
POST {{Contactum.Api_HostAddress}}/api/company/createCompany
Content-Type: application/json

{
    "name": "SuperOffice",
    "description": "SuperOffice CRM."
}


###