@Contactum.Api_HostAddress = http://localhost:5251

POST {{Contactum.Api_HostAddress}}/api/company/createCompany
Content-Type: application/json

{
    "name": "New Company",
    "description": "This is a newly created company."
}


###